### ISSUE TITLE
Trouble building with node v0.11.13

### ISSUE THREAD

**Issue by r-arias** [paixaop/node-sodium#17]
**npm install sodium** fails with a long series of errors on node v0.11.13 on my machine, the first one of which looks like this, and others are quite similar:

    ../sodium.cc: In function ‘v8::Handle<v8::Value> V8Exception(const char*)’:
    ../sodium.cc:72:44: error: ‘New’ is not a member of ‘v8::String’
    ../sodium.cc:72:61: error: ‘ThrowException’ was not declared in this scope
    ../sodium.cc: At global scope:
    ../sodium.cc:76:48: error: ‘Arguments’ does not name a type
    ../sodium.cc:76:59: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from /home/username/.node-gyp/0.11.13/src/node.h:61:0,

What am I doing wrong?
Thank you for your time.

**Comment by donpark** [comment]
My [fork](https://github.com/donpark/node-sodium/tree/libsodium-1.0-update) builds under node.js 0.10, 0.12, and io.js 1.1 (should work with 1.0 as well but haven't tested).

Beware that my fork is offered as-is because my need to keep it updated will fade overtime.

**Comment by jonasfj** [comment]
@donpark, is this a continuation of PR #27 or a separate port?

**Comment by donpark** [comment]
#27 + some extra changes needed for latest V8 which io.js needed. also adds `crypto_box_easy` and `crypto_box_open_easy`.

**Comment by paixaop** [comment]
guys I've merged #27 ad will review @donpark to see if I can merge his changes as well.
